version: '3.8'

services: 
  auth-postgres:
    image: postgres:15.3
    restart: always
    container_name: auth-postgres-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432